# Copyright Glen Knowles 2016 - 2018.
# Distributed under the Boost Software License, Version 1.0.
language: cpp
sudo: false
dist: trusty

matrix:
  include:
    - env: CXX_NAME=g++-6 CC_NAME=gcc-6
      addons:
        apt:
          packages: ['g++-6']
          sources: ubuntu-toolchain-r-test

    - env: CXX_NAME=g++-7 CC_NAME=gcc-7 BUILD_COVERAGE=ON
      addons:
        apt:
          packages: ['g++-7']
          sources: ubuntu-toolchain-r-test
      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - env: CXX_NAME=clang++-3.6 CC_NAME=clang-3.6
      addons:
        apt:
          packages: ['clang-3.6', 'libstdc++-5-dev']
          sources: [llvm-toolchain-precise-3.6, ubuntu-toolchain-r-test]

    - env: CXX_NAME=clang++-5.0 CC_NAME=clang-5.0
      addons:
        apt:
          packages: ['clang-5.0', 'libstdc++-6-dev']
          sources: [llvm-toolchain-trusty-5.0, ubuntu-toolchain-r-test]

script:
  - export CXX=${CXX_NAME} CC=${CC_NAME}
  - mkdir -p build && cd build
  - cmake .. -DBUILD_COVERAGE:BOOL=${BUILD_COVERAGE}
  - cmake --build .
  - ../bin/cli --test

notifications:
  email:
    on_success: change
    on_failure: change
