version: 0.1.{build}

platform:
  - x64
configuration:
  - Debug

before_build:
  - md build\Win64 
  - cd build\Win64
  - cmake -G "Visual Studio 14 2015 Win64" ..\.. 
  - cmake .
  - cd ..\..

build:
  parallel: true
  project: dimcli.sln
  verbosity: minimal

build_script:
  - msbuild dimcli.sln /m /v:minimal /p:Configuration=Debug
  - msbuild dimcli.sln /m /v:minimal /p:Configuration=RelWithDebInfo

after_build:
  - xcopy include build\publish\include\ /s
  - cd build\publish
  - xcopy ..\Win64\lib lib\Win64\ /s
  - copy 
      ..\Win64\src\dimcli.dir\RelWithDebInfo\dimcli.pdb 
      lib\Win64\RelWithDebInfo
  - 7z a dimcli-latest.zip include lib
  - cd ..\..

artifacts:
  - path: build\publish\dimcli-latest.zip
    name: dimcli
    type: zip

test_script:
  - build\Win64\bin\clitest

deploy:
  tag: dimcli-latest
  description: continuous trunk build
  provider: GitHub
  auth_token:
    secure: yheCA/FJ+f7CL84HoPf9MapOlDZQmrGyiqlwFeeIhxvdOudQisUdOyZuWfwq3lUU
  prerelease: true
  draft: false
