version: 0.1.{build}

platform:
  - x64
configuration:
  - Debug

build:
  parallel: true
  project: dimcli.sln
  verbosity: minimal

after_build:
  - 7z a dimcli-v%appveyor_build_version%.zip
      include 
      build\bin\%configuration%\dimcli.*

artifacts:
  - path: dimcli-v$(appveyor_build_version).zip
    name: dimcli
    type: zip

test_script:
  - bin\clitest

deploy:
  tag: dimcli-v$(appveyor_build_version)
  description: continuous trunk build
  provider: GitHub
  auth_token:
    secure: yheCA/FJ+f7CL84HoPf9MapOlDZQmrGyiqlwFeeIhxvdOudQisUdOyZuWfwq3lUU
  prerelease: true
  draft: true
