version: 0.1.{build}
image: 
  - Visual Studio 2015
  - Visual Studio 2017

platform:
  - x64
configuration:
  - Debug

build_script:
  # hack to stop sea of Xamarin (which isn't being used at all) warnings
  # during cmake configuration
  - del "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"

  - md build\Win64 
  - cd build\Win64
  - cmake ..\..
  - cmake -DCMAKE_BUILD_TYPE=%configuration% -DCMAKE_INSTALL_PREFIX=publish .
  - cmake --build . --target install --config %configuration%
  - cd publish
  - 7z a dimcli-latest.zip include lib
  - cd ..\..\..

artifacts:
  - path: build\Win64\publish\dimcli-latest.zip
    name: dimcli
    type: zip

test_script:
  - build\Win64\bin\cli
