version: 0.1.{build}

platform:
  - x64
configuration:
  - Debug

before_build:
  - md build\x64 
  - cd build\x64 
  - cmake -G "Visual Studio 14 2015 Win64" ..\.. 
  - cmake .
  - cd ..\..

build:
  parallel: true
  project: dimcli.sln
  verbosity: minimal

after_build:
  - echo %cd%
  - 7z a dimcli-v%appveyor_build_version%.zip
      include 
      build\x64\bin\%configuration%\dimcli.*

artifacts:
  - path: dimcli-v$(appveyor_build_version).zip
    name: dimcli
    type: zip

test_script:
  - build\x64\bin\clitest

deploy:
  tag: dimcli-v$(appveyor_build_version)
  description: continuous trunk build
  provider: GitHub
  auth_token:
    secure: yheCA/FJ+f7CL84HoPf9MapOlDZQmrGyiqlwFeeIhxvdOudQisUdOyZuWfwq3lUU
  prerelease: true
  draft: true
